from typing import Dict, Any
from llama_index.llms.llama_api import LlamaAPI

class LlamaServiceAPI:

    """
    Class for interacting with the LLAMA API.

    Attributes:
        llm (LlamaAPI): Instance of LlamaAPI for communicating with the LLAMA API.

    Methods:
        get_llm(): Get the LLAMA API instance.
        send_query(query): Send a query to the LLAMA API and retrieve the response.
    """


    def __init__(self,
                 model: str ='llama-7b-chat',
                 api_key: str ='',
                 temperature: float = 0.01,
                 max_tokens: int = 2048,
                 kwargs: Dict[str, Any] = None
                 ) -> None:

        """
        Initialize a LlamaServiceAPI instance.

        Args:
            model (str): Name of the LLAMA model to use. Default is 'llama-7b-chat'.
            api_key (str): API key for accessing the LLAMA API.
            temperature (float): Sampling temperature for generating responses. Default is 0.01.
            max_tokens (int): Maximum number of tokens to generate in the response. Default is 2048.
            kwargs (Dict[str, Any]): Additional keyword arguments for configuring the LLAMA API. Default is None.

        Returns:
            None
        """

        self.llm = LlamaAPI(
            model=model,
            api_key=api_key,
            temperature=temperature,
            max_tokens=max_tokens,
            additional_kwargs=kwargs
        )

    def get_llm(self) -> LlamaAPI:
        """
        Get the LLAMA API instance.

        Returns:
            LlamaAPI: The LLAMA API instance.
        """

        return self.llm

    def send_query(self, query: str) -> str:
        """
        Send a query to the LLAMA API and retrieve the response.

        Args:
            query (str): The query string.

        Returns:
            str: The response generated by the LLAMA API.
        """

        return self.llm.complete(query)
